# Generated by Django 5.1.3 on 2024-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_plate',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
