# Generated by Django 5.1.3 on 2024-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_api', '0002_vehicle_status_alter_vehicle_vehicle_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
